version: '3.7'
networks:
  default:

services:

  db:
    image: mysql:5.7
#    image: woahbase/alpine-mysql
    ports:
    - 127.0.0.1:3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: db
      MYSQL_DATABASE: db
      MYSQL_USER: db
      MYSQL_PASSWORD: db
    networks:
      - default

  python_project:
    image: python_project
    build:
      context: ./../python_project
      dockerfile: Dockerfile
    depends_on:
      - db
    networks:
      - default
    #they let us run an interactive terminal
    stdin_open: true
    tty: true
